### ISSUE TITLE
Missing email conversation

### ISSUE THREAD

**Issue by llrs** [RConsortium/r-repositories-wg#22]
I see that in the meeting on 2022-12-05 there is a summary of an exchange with the CRAN team: 
> The email sent to CRAN with a doodle poll to try to set up a meeting before the end of the year provoked an unhelpful response from BDR.

I am not aware of said exchange, and I thought that no email was sent after last meeting. I was not in the email exchange, while I was in other emails to and from CRAN, and I haven't found it in the Documents folder. Perhaps it won't be added there for privacy concerns, could someone (@joseph-rickert ?) forward me these emails?

**Comment by joseph-rickert** [comment]
Hello Lluis,

email between individuals are generally considered to be confidential. Why
do you want them?

Best regards,
Joe

Joseph B. Rickert
R Consortium Director
Posit R Community Ambassador
408.489.0566

**Comment by llrs** [comment]
Indeed as it should be. I thought that email was sent in name of the working group, as mentioned in [the previous minutes in November](https://github.com/RConsortium/r-repositories-wg/blob/main/minutes/2202-11-07_Minutes.md) in which case I wanted to be in the loop. Sorry! Closing the issue
