### ISSUE TITLE
Next meetings?

### ISSUE THREAD

**Issue by llrs** [RConsortium/r-repositories-wg#24]
There was some trouble last meeting of the working group as it was not clear how to meet and where. There have been some emails for the following meetings and I wanted to confirm the dates and who host them. 
In my calendar I have two meetings at the same hour, which one will be used? 

CRAN - Mon 16 Jan 2023 19:00 – 20:00 (CET) hosted by Luke Schantz. (Linux Foundation)
RRWG - Mon  6 Feb 2023 17:00 – 18:00 (CET) hosted by @joseph-rickert (R Consortium, Posit)
RRWG - Mon  6 Feb 2023 17:00 – 18:00 (CET) hosted by Elisa Trevin (Linux Foundation)

---
I would normaly ask this by email, but it is not clear to me to which email chain is better, as some interested people were left out of last time, so I thought it would be better to confirm this openly.

**Comment by hadley** [comment]
The CRAN discussion on Jan 16 is definitely happening.  I think the Feb 6 call is also likely to happen, and will be hosted by Elisa Trevin.

It would be nice to switch to some alternative system that doesn't require invites to specific individuals, but I'm not sure to how to make it happen. Maybe we could have a public zoom meeting that requires running a small piece of R code to figure out the password? That should make it easy for anyone actually interested to attend while preventing unwanted callers.

**Comment by llrs** [comment]
Thanks for confirming. I thought that as as Luke Schantz presented himself as the one apointed to the R Consortium, it might not be hold with Elisa. 

I think for some events there was the option to register to events in zoom without a human reviewing them. You will know better, I have never created such events (or the R Consortium, the Linux Foundation).

**Comment by lukeschantz** [comment]
Elisa Trevino has moved on to a new venture and is no longer with the company.  She will not be hosting the meeting on the 16th.  I am the new Program Manager and set the meeting on the 16th per @joseph-rickert 's request. You can reach me at lschantz@linuxfoundation.org if you have issues with meeting invites or other questions.  Zoom links have been updated on public calendar events out of necessity and email updates were sent.  I know of one person encountered issue where their calendar did not reflecting a meeting that was canceled.  I have had this sort of thing happen to me as well with Google calendar before.  But I feel confident we can work through these small bumps in the road.
