### ISSUE TITLE
Suggestions to the letter

### ISSUE THREAD

**Issue by llrs** [RConsortium/r-repositories-wg#6]
Sorry I couldn't attend today's meeting.

About the environmental variables used by CRAN some are documented on [R internals](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Tools). I have submitted a PR to r-hub with all the environmental variables I could find (at the time) that are different from default on CRAN: https://github.com/r-hub/rhub/pull/403. Of course, the suggested idea to retrieve them from the svn repository as it can be done with [Bioconductor](https://github.com/Bioconductor/BBS/blob/master/3.15/Renviron.bioc) is much better for the various reasons identified on the email. 

Other than that I would prefer if the goal of this working group could be defined on this email to CRAN.

**Comment by hadley** [comment]
@gaborcsardi can speak to it in more detail, but I don't think the environment variables that R-internals documents that CRAN uses are up to date, and CRAN itself uses a slightly different set than `--as-cran`.

You might've missed that we also updated the README to include a brief statement of goals and list of members: https://github.com/RConsortium/r-repositories-wg. We thought that it would be easier to call out to a website than try and inline all into one email.

**Comment by llrs** [comment]
Hard to say without more information, both of you are more experienced dealing with CRAN submissions and CRAN system than I am but I got the impression that they adhere to the documentation. 

No, I haven't missed the modification of the README, and I was surprised by it. I'm not sure what are the differences between being a member of a working group and contributing to one. Anyway, if the CRAN team is busy they might prefer to just read a sentence or two about that working group without having to go through a link. They might as well, be aware of the WG and this introduction be redundant.

**Comment by gaborcsardi** [comment]
I have some some data from a couple of platforms and unfortunately they are not super consistent. Many machines set additional options, and on macOS they hardly set any of the flags that are supposed to be set according to R-internals.
