### ISSUE TITLE
Minutes of December's meeting

### ISSUE THREAD

**Issue by llrs** [RConsortium/r-repositories-wg#9]
I realized that there aren't any notes of the last meeting on December. Did someone wrote something and it is just missing from the repository?  
Perhaps due to the zoom meeting problems there isn't an official minutes. I could share my notes of the meeting, they are not as detailed as the past meetings but might be enough to know what was discussed and other people can fill in the details I might not written.

**Comment by joseph-rickert** [comment]
Apparently we do not have any minutes. I would very much appreciate it if you could share your notes.

**Comment by llrs** [comment]
I already sent the minutes, I'm not sure they are worth to be posted publicly, so I'm closing now the issue.
